/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteSubdomainRouteImport } from './routes/site.$subdomain'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as EditorDesignIdRouteImport } from './routes/editor.$designId'
import { Route as CardSlugRouteImport } from './routes/card.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedWebsitesIndexRouteImport } from './routes/_authenticated.websites.index'
import { Route as AuthenticatedQrIndexRouteImport } from './routes/_authenticated.qr.index'
import { Route as AuthenticatedDesignsIndexRouteImport } from './routes/_authenticated.designs.index'
import { Route as AuthenticatedBusinessesIndexRouteImport } from './routes/_authenticated.businesses.index'
import { Route as AuthenticatedWebsitesNewRouteImport } from './routes/_authenticated.websites.new'
import { Route as AuthenticatedQrNewRouteImport } from './routes/_authenticated.qr.new'
import { Route as AuthenticatedDesignsNewRouteImport } from './routes/_authenticated.designs.new'
import { Route as AuthenticatedBusinessesNewRouteImport } from './routes/_authenticated.businesses.new'
import { Route as AuthenticatedBusinessesIdRouteImport } from './routes/_authenticated.businesses.$id'
import { Route as AuthenticatedWebsitesIdEditRouteImport } from './routes/_authenticated.websites.$id.edit'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSubdomainRoute = SiteSubdomainRouteImport.update({
  id: '/site/$subdomain',
  path: '/site/$subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorDesignIdRoute = EditorDesignIdRouteImport.update({
  id: '/editor/$designId',
  path: '/editor/$designId',
  getParentRoute: () => rootRouteImport,
} as any)
const CardSlugRoute = CardSlugRouteImport.update({
  id: '/card/$slug',
  path: '/card/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWebsitesIndexRoute =
  AuthenticatedWebsitesIndexRouteImport.update({
    id: '/websites/',
    path: '/websites/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQrIndexRoute = AuthenticatedQrIndexRouteImport.update({
  id: '/qr/',
  path: '/qr/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDesignsIndexRoute =
  AuthenticatedDesignsIndexRouteImport.update({
    id: '/designs/',
    path: '/designs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBusinessesIndexRoute =
  AuthenticatedBusinessesIndexRouteImport.update({
    id: '/businesses/',
    path: '/businesses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWebsitesNewRoute =
  AuthenticatedWebsitesNewRouteImport.update({
    id: '/websites/new',
    path: '/websites/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQrNewRoute = AuthenticatedQrNewRouteImport.update({
  id: '/qr/new',
  path: '/qr/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDesignsNewRoute = AuthenticatedDesignsNewRouteImport.update({
  id: '/designs/new',
  path: '/designs/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBusinessesNewRoute =
  AuthenticatedBusinessesNewRouteImport.update({
    id: '/businesses/new',
    path: '/businesses/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBusinessesIdRoute =
  AuthenticatedBusinessesIdRouteImport.update({
    id: '/businesses/$id',
    path: '/businesses/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWebsitesIdEditRoute =
  AuthenticatedWebsitesIdEditRouteImport.update({
    id: '/websites/$id/edit',
    path: '/websites/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/card/$slug': typeof CardSlugRoute
  '/editor/$designId': typeof EditorDesignIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/site/$subdomain': typeof SiteSubdomainRoute
  '/businesses/$id': typeof AuthenticatedBusinessesIdRoute
  '/businesses/new': typeof AuthenticatedBusinessesNewRoute
  '/designs/new': typeof AuthenticatedDesignsNewRoute
  '/qr/new': typeof AuthenticatedQrNewRoute
  '/websites/new': typeof AuthenticatedWebsitesNewRoute
  '/businesses/': typeof AuthenticatedBusinessesIndexRoute
  '/designs/': typeof AuthenticatedDesignsIndexRoute
  '/qr/': typeof AuthenticatedQrIndexRoute
  '/websites/': typeof AuthenticatedWebsitesIndexRoute
  '/websites/$id/edit': typeof AuthenticatedWebsitesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/card/$slug': typeof CardSlugRoute
  '/editor/$designId': typeof EditorDesignIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/site/$subdomain': typeof SiteSubdomainRoute
  '/businesses/$id': typeof AuthenticatedBusinessesIdRoute
  '/businesses/new': typeof AuthenticatedBusinessesNewRoute
  '/designs/new': typeof AuthenticatedDesignsNewRoute
  '/qr/new': typeof AuthenticatedQrNewRoute
  '/websites/new': typeof AuthenticatedWebsitesNewRoute
  '/businesses': typeof AuthenticatedBusinessesIndexRoute
  '/designs': typeof AuthenticatedDesignsIndexRoute
  '/qr': typeof AuthenticatedQrIndexRoute
  '/websites': typeof AuthenticatedWebsitesIndexRoute
  '/websites/$id/edit': typeof AuthenticatedWebsitesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/card/$slug': typeof CardSlugRoute
  '/editor/$designId': typeof EditorDesignIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/site/$subdomain': typeof SiteSubdomainRoute
  '/_authenticated/businesses/$id': typeof AuthenticatedBusinessesIdRoute
  '/_authenticated/businesses/new': typeof AuthenticatedBusinessesNewRoute
  '/_authenticated/designs/new': typeof AuthenticatedDesignsNewRoute
  '/_authenticated/qr/new': typeof AuthenticatedQrNewRoute
  '/_authenticated/websites/new': typeof AuthenticatedWebsitesNewRoute
  '/_authenticated/businesses/': typeof AuthenticatedBusinessesIndexRoute
  '/_authenticated/designs/': typeof AuthenticatedDesignsIndexRoute
  '/_authenticated/qr/': typeof AuthenticatedQrIndexRoute
  '/_authenticated/websites/': typeof AuthenticatedWebsitesIndexRoute
  '/_authenticated/websites/$id/edit': typeof AuthenticatedWebsitesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/register'
    | '/templates'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/card/$slug'
    | '/editor/$designId'
    | '/oauth/callback'
    | '/site/$subdomain'
    | '/businesses/$id'
    | '/businesses/new'
    | '/designs/new'
    | '/qr/new'
    | '/websites/new'
    | '/businesses/'
    | '/designs/'
    | '/qr/'
    | '/websites/'
    | '/websites/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/register'
    | '/templates'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/card/$slug'
    | '/editor/$designId'
    | '/oauth/callback'
    | '/site/$subdomain'
    | '/businesses/$id'
    | '/businesses/new'
    | '/designs/new'
    | '/qr/new'
    | '/websites/new'
    | '/businesses'
    | '/designs'
    | '/qr'
    | '/websites'
    | '/websites/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/register'
    | '/templates'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/card/$slug'
    | '/editor/$designId'
    | '/oauth/callback'
    | '/site/$subdomain'
    | '/_authenticated/businesses/$id'
    | '/_authenticated/businesses/new'
    | '/_authenticated/designs/new'
    | '/_authenticated/qr/new'
    | '/_authenticated/websites/new'
    | '/_authenticated/businesses/'
    | '/_authenticated/designs/'
    | '/_authenticated/qr/'
    | '/_authenticated/websites/'
    | '/_authenticated/websites/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  TemplatesRoute: typeof TemplatesRoute
  CardSlugRoute: typeof CardSlugRoute
  EditorDesignIdRoute: typeof EditorDesignIdRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  SiteSubdomainRoute: typeof SiteSubdomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$subdomain': {
      id: '/site/$subdomain'
      path: '/site/$subdomain'
      fullPath: '/site/$subdomain'
      preLoaderRoute: typeof SiteSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$designId': {
      id: '/editor/$designId'
      path: '/editor/$designId'
      fullPath: '/editor/$designId'
      preLoaderRoute: typeof EditorDesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$slug': {
      id: '/card/$slug'
      path: '/card/$slug'
      fullPath: '/card/$slug'
      preLoaderRoute: typeof CardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/websites/': {
      id: '/_authenticated/websites/'
      path: '/websites'
      fullPath: '/websites/'
      preLoaderRoute: typeof AuthenticatedWebsitesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qr/': {
      id: '/_authenticated/qr/'
      path: '/qr'
      fullPath: '/qr/'
      preLoaderRoute: typeof AuthenticatedQrIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/designs/': {
      id: '/_authenticated/designs/'
      path: '/designs'
      fullPath: '/designs/'
      preLoaderRoute: typeof AuthenticatedDesignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/businesses/': {
      id: '/_authenticated/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof AuthenticatedBusinessesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/websites/new': {
      id: '/_authenticated/websites/new'
      path: '/websites/new'
      fullPath: '/websites/new'
      preLoaderRoute: typeof AuthenticatedWebsitesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qr/new': {
      id: '/_authenticated/qr/new'
      path: '/qr/new'
      fullPath: '/qr/new'
      preLoaderRoute: typeof AuthenticatedQrNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/designs/new': {
      id: '/_authenticated/designs/new'
      path: '/designs/new'
      fullPath: '/designs/new'
      preLoaderRoute: typeof AuthenticatedDesignsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/businesses/new': {
      id: '/_authenticated/businesses/new'
      path: '/businesses/new'
      fullPath: '/businesses/new'
      preLoaderRoute: typeof AuthenticatedBusinessesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/businesses/$id': {
      id: '/_authenticated/businesses/$id'
      path: '/businesses/$id'
      fullPath: '/businesses/$id'
      preLoaderRoute: typeof AuthenticatedBusinessesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/websites/$id/edit': {
      id: '/_authenticated/websites/$id/edit'
      path: '/websites/$id/edit'
      fullPath: '/websites/$id/edit'
      preLoaderRoute: typeof AuthenticatedWebsitesIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBusinessesIdRoute: typeof AuthenticatedBusinessesIdRoute
  AuthenticatedBusinessesNewRoute: typeof AuthenticatedBusinessesNewRoute
  AuthenticatedDesignsNewRoute: typeof AuthenticatedDesignsNewRoute
  AuthenticatedQrNewRoute: typeof AuthenticatedQrNewRoute
  AuthenticatedWebsitesNewRoute: typeof AuthenticatedWebsitesNewRoute
  AuthenticatedBusinessesIndexRoute: typeof AuthenticatedBusinessesIndexRoute
  AuthenticatedDesignsIndexRoute: typeof AuthenticatedDesignsIndexRoute
  AuthenticatedQrIndexRoute: typeof AuthenticatedQrIndexRoute
  AuthenticatedWebsitesIndexRoute: typeof AuthenticatedWebsitesIndexRoute
  AuthenticatedWebsitesIdEditRoute: typeof AuthenticatedWebsitesIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBusinessesIdRoute: AuthenticatedBusinessesIdRoute,
  AuthenticatedBusinessesNewRoute: AuthenticatedBusinessesNewRoute,
  AuthenticatedDesignsNewRoute: AuthenticatedDesignsNewRoute,
  AuthenticatedQrNewRoute: AuthenticatedQrNewRoute,
  AuthenticatedWebsitesNewRoute: AuthenticatedWebsitesNewRoute,
  AuthenticatedBusinessesIndexRoute: AuthenticatedBusinessesIndexRoute,
  AuthenticatedDesignsIndexRoute: AuthenticatedDesignsIndexRoute,
  AuthenticatedQrIndexRoute: AuthenticatedQrIndexRoute,
  AuthenticatedWebsitesIndexRoute: AuthenticatedWebsitesIndexRoute,
  AuthenticatedWebsitesIdEditRoute: AuthenticatedWebsitesIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  TemplatesRoute: TemplatesRoute,
  CardSlugRoute: CardSlugRoute,
  EditorDesignIdRoute: EditorDesignIdRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  SiteSubdomainRoute: SiteSubdomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
